name: CI
on: [pull_request, push]
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # need to checkout "all commits" for certain features to work (e.g., get all changed files)
      - name: Extract branch name
        id: extract_branch
        uses: keptn/gh-action-extract-branch-name@main
      - name: Print outputs
        run: |
          echo "GIT_SHA=${{ steps.extract_branch.outputs.GIT_SHA }}"
          echo "BRANCH_SLUG=${{ steps.extract_branch.outputs.BRANCH_SLUG }}"
          echo "BRANCH=${{ steps.extract_branch.outputs.BRANCH }}"
      - name: Generate Tag
        id: gen_tag
        run: |
           REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
           echo 'repo name is : $REPO_NAME'
           if [[ ${{ steps.extract_branch.outputs.BRANCH }} == 'master' ]]; then
             TAG=latest
           else
             TAG=${{ steps.extract_branch.outputs.BRANCH }}
           fi
           echo '::set-output name=tag::'$TAG
           echo '::set-output name=repo_name::'$REPO_NAME
      - uses: mr-smithers-excellent/docker-build-push@v3
        name: Build & Push Docker image
        with:
          image: sivakumarvunnam/${{ steps.gen_tag.outputs.REPO_NAME }}
          tag: ${{ steps.gen_tag.outputs.TAG }}
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
